import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fdf8f8",
        "secondary-fixed-dim": "#d0c5b6",
        "primary-container": "#2b2b2b",
        "surface-container-lowest": "#ffffff",
        tertiary: "#081b0b",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#b5cdb3",
        "inverse-primary": "#c8c6c5",
        "on-tertiary-container": "#829981",
        "primary-fixed": "#e4e2e1",
        "secondary-fixed": "#ede1d1",
        "on-secondary-fixed-variant": "#4d463a",
        "on-secondary-fixed": "#201b11",
        background: "#fdf8f8",
        outline: "#747878",
        secondary: "#665d51",
        "secondary-container": "#ede1d1",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#ebe7e7",
        "on-primary-container": "#939292",
        "on-secondary-container": "#6c6357",
        "surface-variant": "#e5e2e1",
        "inverse-surface": "#313030",
        "on-surface-variant": "#444748",
        surface: "#fdf8f8",
        error: "#ba1a1a",
        primary: "#161717",
        "inverse-on-surface": "#f4f0ef",
        "on-tertiary-fixed-variant": "#374c38",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-dim": "#ddd9d8",
        "on-primary-fixed": "#1b1c1c",
        "surface-container-low": "#f7f3f2",
        "tertiary-fixed": "#d1e9ce",
        "surface-container": "#f1edec",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#474746",
        "on-surface": "#1c1b1b",
        "tertiary-container": "#1c301e",
        "surface-tint": "#5f5e5e",
        "on-background": "#1c1b1b",
        "on-error": "#ffffff",
        "outline-variant": "#c4c7c7",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#0c200f",
        "accent-terracotta": "#C86A4A",
        "accent-sage": "#8FA68E",
        "neutral-warm": "#F6F1E8",
        "neutral-border": "#DDD1C2",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "section-gap": "120px",
        unit: "8px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
